# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.mukundrai.com
title: Mukundrai Bros.
email: vora.c@mukundrai.com
author: Chirag Vora
description: Official homepage of Mukundrai Bros. application for Android and iOS
copyright: 'Copyright &copy; 2018 Mukundrai Bros. All Rights Reserved.'
credits: 'Credits: Mukundrai Bros. mobile app is a collective work of <a href="https://www.linkedin.com/in/nitesh-kumar-934083108" target="_blank">Nitesh Kumar</a>, <a href="https://in.linkedin.com/in/rohit-chopra" target="_blank">Rohit Chopra</a>, <a href="https://www.linkedin.com/in/sheik-abdul" target="_blank">Sheik Abdul</a> and <a href="https://www.linkedin.com/in/chirag-vora-ab7ab7165/" target="_blank">Chirag Vora</a>.'




# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: android
    url: https://play.google.com/store/apps/details?id=com.mukundrai.pharmacy
  - title: apple
    url: /coming-soon/ios
