# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.mukundrai.com
title: Mukundrai Bros.
email: vora.c@mukundrai.com
author: Chirag Vora
description: Official homepage of Mukundrai Bros. application for Android and iOS
copyright: 'Copyright &copy; 2018 Mukundrai Bros. All Rights Reserved.'
credits: 'Credits: Mukundrai Bros. mobile app is a collective work of <a href="http://example.com/">Irshad Ahmed, Nikhil Sharma, Nitesh Kumar and Chirag Vora</a>.'




# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: google-play
    url: https://play.google.com/store?hl=en
  - title: apple
    url: https://www.apple.com/in/ios/app-store/
