# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.mukundrai.com
title: Mukundrai Bros.
email: vora.c@mukundrai.com
author: Chirag Vora
description: Official homepage of Mukundrai Bros. application for Android and iOS
copyright: 'Copyright &copy; 2018 Mukundrai Bros. All Rights Reserved.'
credits: 'Credits: Mukundrai Bros. mobile app is a collective work of <a href="http://example.com/">Nitesh Kumar, Rohit Chopra, Nikhil Sharma, Chirag Vora and Irshad Ahmed</a>.'




# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: android
    url: https://play.google.com/store/apps/details?id=com.mukundrai.pharmacy
  - title: apple
    url: /coming-soon/ios
